// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.DB;

namespace Product.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220723102215_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product.DB.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            Description = "Cricket Bat small",
                            ImageId = "cricketbat1",
                            Name = "Cricket_s",
                            Price = 10.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Description = "Cricket Bat medium",
                            ImageId = "cricketbat2",
                            Name = "Cricket_m",
                            Price = 15.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            Color = "white",
                            Description = "Cricket Bat large",
                            ImageId = "cricketbat3",
                            Name = "Cricket_l",
                            Price = 20.0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 5,
                            Color = "red",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton1",
                            Name = "Badminton_s",
                            Price = 10.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton2",
                            Name = "Badminton_m",
                            Price = 15.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 7,
                            Color = "green",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton3",
                            Name = "Badminton_l",
                            Price = 20.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 8,
                            Color = "blue",
                            Description = "rugby league and rugby union",
                            ImageId = "rogby1",
                            Name = "rugby_s",
                            Price = 5.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            Description = "rugby league and rugby union",
                            ImageId = "rogby2",
                            Name = "rugby_m",
                            Price = 10.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 10,
                            Color = "blue",
                            Description = "rugby league and rugby union",
                            ImageId = "rogby3",
                            Name = "rugby_l",
                            Price = 15.0,
                            Size = "medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
