// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.DB;

namespace Product.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220722000135_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product.DB.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            Description = "Cricket Bat",
                            Name = "Cricket",
                            Size = "small"
                        },
                        new
                        {
                            Id = 2,
                            Color = "white",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            Name = "Badminton",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            Color = "blue",
                            Description = "rugby league and rugby union",
                            Name = "rugby ",
                            Size = "medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
