// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.DB;

namespace Product.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220726151543_initials3")]
    partial class initials3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product.DB.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            Description = "A cricket bat is a specialised piece of equipment used by batters in the sport of cricket to hit the ball, typically consisting of a cane handle attached to a flat-fronted willow-wood blade. It may also be used by a batter who is making ground to avoid a run out, by holding the bat and touching the ground with it.",
                            ImageId = "cricketbat1",
                            Name = "Cricket_s",
                            Price = 10.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Description = "As a rule, the full length of a cricket bat should reach to just below the waist on the cricketer",
                            ImageId = "cricketbat2",
                            Name = "Cricket_m",
                            Price = 15.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            Color = "white",
                            Description = "As a rule, the full length of a cricket bat should reach to just below the waist on the cricketer",
                            ImageId = "cricketbat3",
                            Name = "Cricket_l",
                            Price = 20.0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 5,
                            Color = "red",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton1",
                            Name = "Badminton_s",
                            Price = 10.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 6,
                            Color = "white",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton2",
                            Name = "Badminton_m",
                            Price = 15.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 7,
                            Color = "green",
                            Description = "Badminton is a racquet sport played using racquets to hit a shuttlecock across a net",
                            ImageId = "badminton3",
                            Name = "Badminton_l",
                            Price = 20.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 8,
                            Color = "blue",
                            Description = "Rugby was invented in the early 19th century as a variation on football. It is a team sport where each player can really go all out. Rugby is a 15-a-side team sport. The object of the game is to ground the ball behind the opponent's try line, into what is called the in-goal area.",
                            ImageId = "rogby1",
                            Name = "rugby_s",
                            Price = 5.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 9,
                            Color = "red",
                            Description = "Rugby was invented in the early 19th century as a variation on football. It is a team sport where each player can really go all out. Rugby is a 15-a-side team sport. The object of the game is to ground the ball behind the opponent's try line, into what is called the in-goal area.",
                            ImageId = "rogby2",
                            Name = "rugby_m",
                            Price = 20.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 10,
                            Color = "white",
                            Description = "Rugby was invented in the early 19th century as a variation on football. It is a team sport where each player can really go all out. Rugby is a 15-a-side team sport. The object of the game is to ground the ball behind the opponent's try line, into what is called the in-goal area.",
                            ImageId = "rogby3",
                            Name = "rugby_l",
                            Price = 30.0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 11,
                            Color = "red",
                            Description = "A T-shirt, or tee shirt, was originally worn only by men as an undershirt. Now it is defined as a short-sleeved, collarless undershirt or any outer shirt of a similar design.",
                            ImageId = "tshirt1",
                            Name = "T-shirt",
                            Price = 50.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 12,
                            Color = "black",
                            Description = "A T-shirt, or tee shirt, was originally worn only by men as an undershirt. Now it is defined as a short-sleeved, collarless undershirt or any outer shirt of a similar design.",
                            ImageId = "tshirt2",
                            Name = "T-shirt-m",
                            Price = 25.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 13,
                            Color = "black",
                            Description = "A T-shirt, or tee shirt, was originally worn only by men as an undershirt. Now it is defined as a short-sleeved, collarless undershirt or any outer shirt of a similar design.",
                            ImageId = "tshirt3",
                            Name = "T-shirt-m",
                            Price = 20.0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 14,
                            Color = "gray",
                            Description = "Shoes not only help our feet to heal but can also aid in support and stability of our foot. Not all feet are perfect, so properly fitting shoes can help align your feet, ankles, knees, hips and back to correct your gait and improve posture.",
                            ImageId = "Shoes1",
                            Name = "Shoes_s",
                            Price = 100.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 15,
                            Color = "black",
                            Description = "Shoes not only help our feet to heal but can also aid in support and stability of our foot. Not all feet are perfect, so properly fitting shoes can help align your feet, ankles, knees, hips and back to correct your gait and improve posture.",
                            ImageId = "Shoes2",
                            Name = "Shoes_m",
                            Price = 80.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 16,
                            Color = "red",
                            Description = "Shoes not only help our feet to heal but can also aid in support and stability of our foot. Not all feet are perfect, so properly fitting shoes can help align your feet, ankles, knees, hips and back to correct your gait and improve posture.",
                            ImageId = "Shoes3",
                            Name = "Shoes_l",
                            Price = 60.0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 17,
                            Color = "blue",
                            Description = "It is designed to keep a consistent movement despite the motions caused by the person's activities. A wristwatch is designed to be worn around the wrist, attached by a watch strap or other type of bracelet, including metal bands, leather straps or any other kind of bracelet.",
                            ImageId = "watch1",
                            Name = "wrist_watch-s",
                            Price = 150.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 18,
                            Color = "black",
                            Description = "It is designed to keep a consistent movement despite the motions caused by the person's activities. A wristwatch is designed to be worn around the wrist, attached by a watch strap or other type of bracelet, including metal bands, leather straps or any other kind of bracelet.",
                            ImageId = "watch2",
                            Name = "wrist_watch-m",
                            Price = 100.0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 19,
                            Color = "white",
                            Description = "It is designed to keep a consistent movement despite the motions caused by the person's activities. A wristwatch is designed to be worn around the wrist, attached by a watch strap or other type of bracelet, including metal bands, leather straps or any other kind of bracelet.",
                            ImageId = "watch3",
                            Name = "wrist_watch-l",
                            Price = 70.0,
                            Size = "large"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
